version: '3.6'
services:
  uninet-dev-db:
    image: postgres
    container_name: uninet-dev-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: uninet
    ports:
      - 5434:5432
    volumes:
      - ./db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql