version: '3.6'
services:
  uninet-dev-db:
    image: postgres
    container_name: uninet-dev-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: uninet
    ports:
      - 5434:5432
